apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: java-fla-quarkus 
  janus-idp.io/tekton: java-fla-quarkus
  backstage.io/kubernetes-id: java-fla-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: java-fla-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  